# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XnatUI.ui'
#
# Created: Mon Sep 12 11:05:22 2016
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1353, 995)
        MainWindow.setMinimumSize(QtCore.QSize(1325, 904))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.horizontalLayout_4.addWidget(self.splitter_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lbl_host = QtGui.QLabel(self.centralwidget)
        self.lbl_host.setObjectName(_fromUtf8("lbl_host"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_host)
        self.edt_host = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edt_host.sizePolicy().hasHeightForWidth())
        self.edt_host.setSizePolicy(sizePolicy)
        self.edt_host.setMinimumSize(QtCore.QSize(250, 25))
        self.edt_host.setMaximumSize(QtCore.QSize(150, 100))
        self.edt_host.setToolTip(_fromUtf8(""))
        self.edt_host.setWhatsThis(_fromUtf8(""))
        self.edt_host.setObjectName(_fromUtf8("edt_host"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.edt_host)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.line_3)
        self.lbl_username = QtGui.QLabel(self.centralwidget)
        self.lbl_username.setObjectName(_fromUtf8("lbl_username"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_username)
        self.edt_username = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edt_username.sizePolicy().hasHeightForWidth())
        self.edt_username.setSizePolicy(sizePolicy)
        self.edt_username.setMinimumSize(QtCore.QSize(250, 25))
        self.edt_username.setMaximumSize(QtCore.QSize(150, 100))
        self.edt_username.setToolTip(_fromUtf8(""))
        self.edt_username.setWhatsThis(_fromUtf8(""))
        self.edt_username.setObjectName(_fromUtf8("edt_username"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.edt_username)
        self.lbl_pwd = QtGui.QLabel(self.centralwidget)
        self.lbl_pwd.setObjectName(_fromUtf8("lbl_pwd"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl_pwd)
        self.edt_pwd = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edt_pwd.sizePolicy().hasHeightForWidth())
        self.edt_pwd.setSizePolicy(sizePolicy)
        self.edt_pwd.setMinimumSize(QtCore.QSize(250, 25))
        self.edt_pwd.setMaximumSize(QtCore.QSize(150, 100))
        self.edt_pwd.setToolTip(_fromUtf8(""))
        self.edt_pwd.setWhatsThis(_fromUtf8(""))
        self.edt_pwd.setEchoMode(QtGui.QLineEdit.Password)
        self.edt_pwd.setObjectName(_fromUtf8("edt_pwd"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.edt_pwd)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btn_SignIn = QtGui.QPushButton(self.centralwidget)
        self.btn_SignIn.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_SignIn.setMaximumSize(QtCore.QSize(100, 100))
        self.btn_SignIn.setToolTip(_fromUtf8(""))
        self.btn_SignIn.setWhatsThis(_fromUtf8(""))
        self.btn_SignIn.setObjectName(_fromUtf8("btn_SignIn"))
        self.horizontalLayout_6.addWidget(self.btn_SignIn)
        self.lbl_status = QtGui.QLabel(self.centralwidget)
        self.lbl_status.setMinimumSize(QtCore.QSize(0, 30))
        self.lbl_status.setMaximumSize(QtCore.QSize(300, 30))
        self.lbl_status.setStyleSheet(_fromUtf8("background-color: #ffffcc;"))
        self.lbl_status.setText(_fromUtf8(""))
        self.lbl_status.setObjectName(_fromUtf8("lbl_status"))
        self.horizontalLayout_6.addWidget(self.lbl_status)
        self.formLayout.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.horizontalLayout.addLayout(self.formLayout)
        self.grp_log = QtGui.QGroupBox(self.centralwidget)
        self.grp_log.setObjectName(_fromUtf8("grp_log"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.grp_log)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.edt_log_path = QtGui.QLineEdit(self.grp_log)
        self.edt_log_path.setMinimumSize(QtCore.QSize(100, 30))
        self.edt_log_path.setMaximumSize(QtCore.QSize(400, 30))
        self.edt_log_path.setObjectName(_fromUtf8("edt_log_path"))
        self.verticalLayout_7.addWidget(self.edt_log_path)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btn_log_browse = QtGui.QPushButton(self.grp_log)
        self.btn_log_browse.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_log_browse.setMaximumSize(QtCore.QSize(120, 30))
        self.btn_log_browse.setObjectName(_fromUtf8("btn_log_browse"))
        self.horizontalLayout_5.addWidget(self.btn_log_browse)
        self.grp_log_type = QtGui.QGroupBox(self.grp_log)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_log_type.sizePolicy().hasHeightForWidth())
        self.grp_log_type.setSizePolicy(sizePolicy)
        self.grp_log_type.setObjectName(_fromUtf8("grp_log_type"))
        self.rb_log_detailed = QtGui.QRadioButton(self.grp_log_type)
        self.rb_log_detailed.setGeometry(QtCore.QRect(20, 30, 101, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_log_detailed.sizePolicy().hasHeightForWidth())
        self.rb_log_detailed.setSizePolicy(sizePolicy)
        self.rb_log_detailed.setMinimumSize(QtCore.QSize(20, 10))
        self.rb_log_detailed.setObjectName(_fromUtf8("rb_log_detailed"))
        self.rb_log_short = QtGui.QRadioButton(self.grp_log_type)
        self.rb_log_short.setGeometry(QtCore.QRect(140, 30, 82, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_log_short.sizePolicy().hasHeightForWidth())
        self.rb_log_short.setSizePolicy(sizePolicy)
        self.rb_log_short.setMinimumSize(QtCore.QSize(20, 10))
        self.rb_log_short.setObjectName(_fromUtf8("rb_log_short"))
        self.horizontalLayout_5.addWidget(self.grp_log_type)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addWidget(self.grp_log)
        self.grp_Project = QtGui.QFrame(self.centralwidget)
        self.grp_Project.setMinimumSize(QtCore.QSize(400, 80))
        self.grp_Project.setObjectName(_fromUtf8("grp_Project"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.grp_Project)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.grp_project = QtGui.QGroupBox(self.grp_Project)
        self.grp_project.setObjectName(_fromUtf8("grp_project"))
        self.cmb_project = QtGui.QComboBox(self.grp_project)
        self.cmb_project.setGeometry(QtCore.QRect(0, 20, 380, 30))
        self.cmb_project.setMinimumSize(QtCore.QSize(200, 30))
        self.cmb_project.setToolTip(_fromUtf8(""))
        self.cmb_project.setWhatsThis(_fromUtf8(""))
        self.cmb_project.setObjectName(_fromUtf8("cmb_project"))
        self.verticalLayout_9.addWidget(self.grp_project)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.btn_refresh = QtGui.QPushButton(self.grp_Project)
        self.btn_refresh.setObjectName(_fromUtf8("btn_refresh"))
        self.horizontalLayout_7.addWidget(self.btn_refresh)
        self.btn_reset = QtGui.QPushButton(self.grp_Project)
        self.btn_reset.setObjectName(_fromUtf8("btn_reset"))
        self.horizontalLayout_7.addWidget(self.btn_reset)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout.addWidget(self.grp_Project)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout.addWidget(self.line_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btn_page1 = QtGui.QPushButton(self.centralwidget)
        self.btn_page1.setMinimumSize(QtCore.QSize(50, 20))
        self.btn_page1.setToolTip(_fromUtf8(""))
        self.btn_page1.setWhatsThis(_fromUtf8(""))
        self.btn_page1.setObjectName(_fromUtf8("btn_page1"))
        self.horizontalLayout_3.addWidget(self.btn_page1)
        self.btn_page2 = QtGui.QPushButton(self.centralwidget)
        self.btn_page2.setMinimumSize(QtCore.QSize(50, 20))
        self.btn_page2.setToolTip(_fromUtf8(""))
        self.btn_page2.setWhatsThis(_fromUtf8(""))
        self.btn_page2.setObjectName(_fromUtf8("btn_page2"))
        self.horizontalLayout_3.addWidget(self.btn_page2)
        self.btn_page3 = QtGui.QPushButton(self.centralwidget)
        self.btn_page3.setMinimumSize(QtCore.QSize(50, 20))
        self.btn_page3.setToolTip(_fromUtf8(""))
        self.btn_page3.setWhatsThis(_fromUtf8(""))
        self.btn_page3.setObjectName(_fromUtf8("btn_page3"))
        self.horizontalLayout_3.addWidget(self.btn_page3)
        self.btn_page4 = QtGui.QPushButton(self.centralwidget)
        self.btn_page4.setMinimumSize(QtCore.QSize(50, 20))
        self.btn_page4.setToolTip(_fromUtf8(""))
        self.btn_page4.setWhatsThis(_fromUtf8(""))
        self.btn_page4.setObjectName(_fromUtf8("btn_page4"))
        self.horizontalLayout_3.addWidget(self.btn_page4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_12 = QtGui.QFrame(self.centralwidget)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.verticalLayout.addWidget(self.line_12)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(600, 600))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_what = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_what.sizePolicy().hasHeightForWidth())
        self.page_what.setSizePolicy(sizePolicy)
        self.page_what.setObjectName(_fromUtf8("page_what"))
        self.splitter_6 = QtGui.QSplitter(self.page_what)
        self.splitter_6.setGeometry(QtCore.QRect(11, 1, 1291, 591))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_6.sizePolicy().hasHeightForWidth())
        self.splitter_6.setSizePolicy(sizePolicy)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName(_fromUtf8("splitter_6"))
        self.layoutWidget = QtGui.QWidget(self.splitter_6)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lbl_sub = QtGui.QLabel(self.layoutWidget)
        self.lbl_sub.setObjectName(_fromUtf8("lbl_sub"))
        self.verticalLayout_5.addWidget(self.lbl_sub)
        self.chk_sub = QtGui.QCheckBox(self.layoutWidget)
        self.chk_sub.setToolTip(_fromUtf8(""))
        self.chk_sub.setWhatsThis(_fromUtf8(""))
        self.chk_sub.setObjectName(_fromUtf8("chk_sub"))
        self.verticalLayout_5.addWidget(self.chk_sub)
        self.lst_subjects = QtGui.QListWidget(self.layoutWidget)
        self.lst_subjects.setToolTip(_fromUtf8(""))
        self.lst_subjects.setObjectName(_fromUtf8("lst_subjects"))
        self.verticalLayout_5.addWidget(self.lst_subjects)
        self.layoutWidget1 = QtGui.QWidget(self.splitter_6)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lbl_sess = QtGui.QLabel(self.layoutWidget1)
        self.lbl_sess.setObjectName(_fromUtf8("lbl_sess"))
        self.verticalLayout_4.addWidget(self.lbl_sess)
        self.chk_sess = QtGui.QCheckBox(self.layoutWidget1)
        self.chk_sess.setToolTip(_fromUtf8(""))
        self.chk_sess.setWhatsThis(_fromUtf8(""))
        self.chk_sess.setObjectName(_fromUtf8("chk_sess"))
        self.verticalLayout_4.addWidget(self.chk_sess)
        self.tree_sessions = QtGui.QTreeWidget(self.layoutWidget1)
        self.tree_sessions.setToolTip(_fromUtf8(""))
        self.tree_sessions.setObjectName(_fromUtf8("tree_sessions"))
        self.tree_sessions.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_4.addWidget(self.tree_sessions)
        self.layoutWidget2 = QtGui.QWidget(self.splitter_6)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lbl_scan = QtGui.QLabel(self.layoutWidget2)
        self.lbl_scan.setObjectName(_fromUtf8("lbl_scan"))
        self.verticalLayout_3.addWidget(self.lbl_scan)
        self.chk_scan = QtGui.QCheckBox(self.layoutWidget2)
        self.chk_scan.setToolTip(_fromUtf8(""))
        self.chk_scan.setWhatsThis(_fromUtf8(""))
        self.chk_scan.setObjectName(_fromUtf8("chk_scan"))
        self.verticalLayout_3.addWidget(self.chk_scan)
        self.tree_scans = QtGui.QTreeWidget(self.layoutWidget2)
        self.tree_scans.setToolTip(_fromUtf8(""))
        self.tree_scans.setObjectName(_fromUtf8("tree_scans"))
        self.tree_scans.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_3.addWidget(self.tree_scans)
        self.stackedWidget.addWidget(self.page_what)
        self.page_where = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_where.sizePolicy().hasHeightForWidth())
        self.page_where.setSizePolicy(sizePolicy)
        self.page_where.setObjectName(_fromUtf8("page_where"))
        self.splitter_8 = QtGui.QSplitter(self.page_where)
        self.splitter_8.setGeometry(QtCore.QRect(10, 0, 1291, 591))
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName(_fromUtf8("splitter_8"))
        self.gridGroupBox = QtGui.QGroupBox(self.splitter_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridGroupBox.sizePolicy().hasHeightForWidth())
        self.gridGroupBox.setSizePolicy(sizePolicy)
        self.gridGroupBox.setObjectName(_fromUtf8("gridGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter_7 = QtGui.QSplitter(self.gridGroupBox)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName(_fromUtf8("splitter_7"))
        self.splitter = QtGui.QSplitter(self.splitter_7)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget3 = QtGui.QWidget(self.splitter)
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.edt_path_txt = QtGui.QLineEdit(self.layoutWidget3)
        self.edt_path_txt.setMinimumSize(QtCore.QSize(50, 30))
        self.edt_path_txt.setObjectName(_fromUtf8("edt_path_txt"))
        self.gridLayout.addWidget(self.edt_path_txt, 0, 0, 1, 1)
        self.btn_send_edt = QtGui.QPushButton(self.layoutWidget3)
        self.btn_send_edt.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_send_edt.setObjectName(_fromUtf8("btn_send_edt"))
        self.gridLayout.addWidget(self.btn_send_edt, 0, 1, 1, 1)
        self.btn_send_cmb = QtGui.QPushButton(self.layoutWidget3)
        self.btn_send_cmb.setMinimumSize(QtCore.QSize(50, 30))
        self.btn_send_cmb.setObjectName(_fromUtf8("btn_send_cmb"))
        self.gridLayout.addWidget(self.btn_send_cmb, 1, 1, 1, 1)
        self.cmb_path_txt = QtGui.QComboBox(self.layoutWidget3)
        self.cmb_path_txt.setMinimumSize(QtCore.QSize(50, 30))
        self.cmb_path_txt.setObjectName(_fromUtf8("cmb_path_txt"))
        self.gridLayout.addWidget(self.cmb_path_txt, 1, 0, 1, 1)
        self.grp_reset_paths = QtGui.QGroupBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_reset_paths.sizePolicy().hasHeightForWidth())
        self.grp_reset_paths.setSizePolicy(sizePolicy)
        self.grp_reset_paths.setMinimumSize(QtCore.QSize(100, 100))
        self.grp_reset_paths.setObjectName(_fromUtf8("grp_reset_paths"))
        self.btn_reset_path_selected = QtGui.QPushButton(self.grp_reset_paths)
        self.btn_reset_path_selected.setGeometry(QtCore.QRect(60, 20, 100, 35))
        self.btn_reset_path_selected.setMinimumSize(QtCore.QSize(100, 35))
        self.btn_reset_path_selected.setObjectName(_fromUtf8("btn_reset_path_selected"))
        self.btn_reset_path_all = QtGui.QPushButton(self.grp_reset_paths)
        self.btn_reset_path_all.setGeometry(QtCore.QRect(60, 60, 100, 35))
        self.btn_reset_path_all.setMinimumSize(QtCore.QSize(100, 35))
        self.btn_reset_path_all.setObjectName(_fromUtf8("btn_reset_path_all"))
        self.btn_mk_bids = QtGui.QPushButton(self.grp_reset_paths)
        self.btn_mk_bids.setGeometry(QtCore.QRect(170, 20, 100, 35))
        self.btn_mk_bids.setMinimumSize(QtCore.QSize(100, 35))
        self.btn_mk_bids.setObjectName(_fromUtf8("btn_mk_bids"))
        self.chk_BIDS_extra = QtGui.QCheckBox(self.grp_reset_paths)
        self.chk_BIDS_extra.setGeometry(QtCore.QRect(180, 60, 150, 35))
        self.chk_BIDS_extra.setMinimumSize(QtCore.QSize(100, 35))
        self.chk_BIDS_extra.setObjectName(_fromUtf8("chk_BIDS_extra"))
        self.grp_send_path_loc = QtGui.QGroupBox(self.splitter_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_send_path_loc.sizePolicy().hasHeightForWidth())
        self.grp_send_path_loc.setSizePolicy(sizePolicy)
        self.grp_send_path_loc.setObjectName(_fromUtf8("grp_send_path_loc"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.grp_send_path_loc)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.rb_send_path = QtGui.QRadioButton(self.grp_send_path_loc)
        self.rb_send_path.setObjectName(_fromUtf8("rb_send_path"))
        self.horizontalLayout_2.addWidget(self.rb_send_path)
        self.rb_send_file = QtGui.QRadioButton(self.grp_send_path_loc)
        self.rb_send_file.setMinimumSize(QtCore.QSize(200, 30))
        self.rb_send_file.setObjectName(_fromUtf8("rb_send_file"))
        self.horizontalLayout_2.addWidget(self.rb_send_file)
        self.gridLayout_2.addWidget(self.splitter_7, 0, 0, 1, 1)
        self.grp_path = QtGui.QGroupBox(self.splitter_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_path.sizePolicy().hasHeightForWidth())
        self.grp_path.setSizePolicy(sizePolicy)
        self.grp_path.setMinimumSize(QtCore.QSize(600, 250))
        self.grp_path.setObjectName(_fromUtf8("grp_path"))
        self.stackedWidget.addWidget(self.page_where)
        self.page_how = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_how.sizePolicy().hasHeightForWidth())
        self.page_how.setSizePolicy(sizePolicy)
        self.page_how.setObjectName(_fromUtf8("page_how"))
        self.splitter_5 = QtGui.QSplitter(self.page_how)
        self.splitter_5.setGeometry(QtCore.QRect(10, 10, 1291, 581))
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName(_fromUtf8("splitter_5"))
        self.splitter_4 = QtGui.QSplitter(self.splitter_5)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName(_fromUtf8("splitter_4"))
        self.lst_sel_log = QtGui.QListWidget(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lst_sel_log.sizePolicy().hasHeightForWidth())
        self.lst_sel_log.setSizePolicy(sizePolicy)
        self.lst_sel_log.setMinimumSize(QtCore.QSize(0, 450))
        self.lst_sel_log.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lst_sel_log.setObjectName(_fromUtf8("lst_sel_log"))
        self.lst_dest_pick = QtGui.QListWidget(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lst_dest_pick.sizePolicy().hasHeightForWidth())
        self.lst_dest_pick.setSizePolicy(sizePolicy)
        self.lst_dest_pick.setMinimumSize(QtCore.QSize(0, 450))
        self.lst_dest_pick.setObjectName(_fromUtf8("lst_dest_pick"))
        self.lst_filename = QtGui.QListWidget(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lst_filename.sizePolicy().hasHeightForWidth())
        self.lst_filename.setSizePolicy(sizePolicy)
        self.lst_filename.setMinimumSize(QtCore.QSize(0, 450))
        self.lst_filename.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lst_filename.setObjectName(_fromUtf8("lst_filename"))
        self.lst_cmd = QtGui.QListWidget(self.splitter_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lst_cmd.sizePolicy().hasHeightForWidth())
        self.lst_cmd.setSizePolicy(sizePolicy)
        self.lst_cmd.setMinimumSize(QtCore.QSize(0, 450))
        self.lst_cmd.setObjectName(_fromUtf8("lst_cmd"))
        self.splitter_3 = QtGui.QSplitter(self.splitter_5)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.grp_down_type = QtGui.QGroupBox(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_down_type.sizePolicy().hasHeightForWidth())
        self.grp_down_type.setSizePolicy(sizePolicy)
        self.grp_down_type.setMinimumSize(QtCore.QSize(0, 70))
        self.grp_down_type.setObjectName(_fromUtf8("grp_down_type"))
        self.gridLayout_3 = QtGui.QGridLayout(self.grp_down_type)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.rb_afni = QtGui.QRadioButton(self.grp_down_type)
        self.rb_afni.setObjectName(_fromUtf8("rb_afni"))
        self.gridLayout_3.addWidget(self.rb_afni, 1, 0, 1, 1)
        self.rb_custom = QtGui.QRadioButton(self.grp_down_type)
        self.rb_custom.setObjectName(_fromUtf8("rb_custom"))
        self.gridLayout_3.addWidget(self.rb_custom, 1, 1, 1, 1)
        self.rb_nifti = QtGui.QRadioButton(self.grp_down_type)
        self.rb_nifti.setObjectName(_fromUtf8("rb_nifti"))
        self.gridLayout_3.addWidget(self.rb_nifti, 0, 1, 1, 1)
        self.rb_dcm = QtGui.QRadioButton(self.grp_down_type)
        self.rb_dcm.setObjectName(_fromUtf8("rb_dcm"))
        self.gridLayout_3.addWidget(self.rb_dcm, 0, 0, 1, 1)
        self.grp_down_cmd = QtGui.QGroupBox(self.splitter_3)
        self.grp_down_cmd.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_down_cmd.sizePolicy().hasHeightForWidth())
        self.grp_down_cmd.setSizePolicy(sizePolicy)
        self.grp_down_cmd.setMinimumSize(QtCore.QSize(1000, 100))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.grp_down_cmd.setFont(font)
        self.grp_down_cmd.setObjectName(_fromUtf8("grp_down_cmd"))
        self.edt_down_cmd = QtGui.QLineEdit(self.grp_down_cmd)
        self.edt_down_cmd.setGeometry(QtCore.QRect(10, 30, 981, 20))
        self.edt_down_cmd.setMinimumSize(QtCore.QSize(150, 0))
        self.edt_down_cmd.setObjectName(_fromUtf8("edt_down_cmd"))
        self.btn_download = QtGui.QPushButton(self.grp_down_cmd)
        self.btn_download.setGeometry(QtCore.QRect(920, 60, 171, 31))
        self.btn_download.setObjectName(_fromUtf8("btn_download"))
        self.btn_refresh_cmd = QtGui.QPushButton(self.grp_down_cmd)
        self.btn_refresh_cmd.setGeometry(QtCore.QRect(1000, 22, 91, 31))
        self.btn_refresh_cmd.setStatusTip(_fromUtf8(""))
        self.btn_refresh_cmd.setWhatsThis(_fromUtf8(""))
        self.btn_refresh_cmd.setObjectName(_fromUtf8("btn_refresh_cmd"))
        self.edt_down_status = QtGui.QLineEdit(self.grp_down_cmd)
        self.edt_down_status.setEnabled(True)
        self.edt_down_status.setGeometry(QtCore.QRect(10, 70, 471, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edt_down_status.sizePolicy().hasHeightForWidth())
        self.edt_down_status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.edt_down_status.setFont(font)
        self.edt_down_status.setReadOnly(True)
        self.edt_down_status.setObjectName(_fromUtf8("edt_down_status"))
        self.stackedWidget.addWidget(self.page_how)
        self.page_process = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_process.sizePolicy().hasHeightForWidth())
        self.page_process.setSizePolicy(sizePolicy)
        self.page_process.setObjectName(_fromUtf8("page_process"))
        self.stackedWidget.addWidget(self.page_process)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.pb_inter = QtGui.QProgressBar(self.centralwidget)
        self.pb_inter.setMinimumSize(QtCore.QSize(0, 20))
        self.pb_inter.setToolTip(_fromUtf8(""))
        self.pb_inter.setProperty("value", 24)
        self.pb_inter.setObjectName(_fromUtf8("pb_inter"))
        self.verticalLayout.addWidget(self.pb_inter)
        self.pb_final = QtGui.QProgressBar(self.centralwidget)
        self.pb_final.setMinimumSize(QtCore.QSize(0, 20))
        self.pb_final.setProperty("value", 24)
        self.pb_final.setObjectName(_fromUtf8("pb_final"))
        self.verticalLayout.addWidget(self.pb_final)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1315, 72))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.txt_log = QtGui.QTextBrowser(self.scrollAreaWidgetContents)
        self.txt_log.setMinimumSize(QtCore.QSize(0, 50))
        self.txt_log.setToolTip(_fromUtf8(""))
        self.txt_log.setAutoFillBackground(True)
        self.txt_log.setObjectName(_fromUtf8("txt_log"))
        self.verticalLayout_2.addWidget(self.txt_log)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1353, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Xnat Downloader", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_host.setText(QtGui.QApplication.translate("MainWindow", "Xnat Host:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_username.setText(QtGui.QApplication.translate("MainWindow", "Username :", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_pwd.setText(QtGui.QApplication.translate("MainWindow", "Password :", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_SignIn.setText(QtGui.QApplication.translate("MainWindow", "Sign In", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_log.setTitle(QtGui.QApplication.translate("MainWindow", "Log File Location", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_log_browse.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_log_type.setTitle(QtGui.QApplication.translate("MainWindow", "Logging Type", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_log_detailed.setText(QtGui.QApplication.translate("MainWindow", "Detailed Log", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_log_short.setText(QtGui.QApplication.translate("MainWindow", "Short Log", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_project.setTitle(QtGui.QApplication.translate("MainWindow", "Select Project", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_refresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_reset.setText(QtGui.QApplication.translate("MainWindow", "Reset All", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_page1.setText(QtGui.QApplication.translate("MainWindow", "1. Source", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_page2.setText(QtGui.QApplication.translate("MainWindow", "2. Destination", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_page3.setText(QtGui.QApplication.translate("MainWindow", "3.a Download", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_page4.setText(QtGui.QApplication.translate("MainWindow", "3.b Process", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_sub.setText(QtGui.QApplication.translate("MainWindow", "Select Subjects", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_sub.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_sess.setText(QtGui.QApplication.translate("MainWindow", "Select Sessions", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_sess.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_scan.setText(QtGui.QApplication.translate("MainWindow", "Select Scans", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_scan.setText(QtGui.QApplication.translate("MainWindow", "Select All", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_send_edt.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_send_cmb.setText(QtGui.QApplication.translate("MainWindow", "Send", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_reset_paths.setTitle(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_reset_path_selected.setText(QtGui.QApplication.translate("MainWindow", "Reset Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_reset_path_all.setText(QtGui.QApplication.translate("MainWindow", "Reset All", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_mk_bids.setText(QtGui.QApplication.translate("MainWindow", "Make BIDS Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_BIDS_extra.setText(QtGui.QApplication.translate("MainWindow", "Download BIDS Xtra FIles", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_send_path_loc.setTitle(QtGui.QApplication.translate("MainWindow", "Where to Send", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_send_path.setText(QtGui.QApplication.translate("MainWindow", "Send to PATH name", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_send_file.setText(QtGui.QApplication.translate("MainWindow", "Send to FILE name", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_path.setTitle(QtGui.QApplication.translate("MainWindow", "Create Unique Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_down_type.setTitle(QtGui.QApplication.translate("MainWindow", "Select Format", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_afni.setText(QtGui.QApplication.translate("MainWindow", "AFNI", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_custom.setText(QtGui.QApplication.translate("MainWindow", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_nifti.setText(QtGui.QApplication.translate("MainWindow", "NIFTI", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_dcm.setText(QtGui.QApplication.translate("MainWindow", "DICOM", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_down_cmd.setTitle(QtGui.QApplication.translate("MainWindow", "Conversion Script", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_download.setText(QtGui.QApplication.translate("MainWindow", "DOWNLOAD", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_refresh_cmd.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.edt_down_status.setText(QtGui.QApplication.translate("MainWindow", "Status: Ready", None, QtGui.QApplication.UnicodeUTF8))

